name: Test
on: [push]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.1
          cache: npm
        
      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run TypeScript Compiler
        run: npm run workflow
